### ISSUE TITLE
rtg-serve uses Flask but doesn't install it

### ISSUE THREAD

**Issue by saurabhj80** [isi-nlp/rtg#3]
```
[04-17 20:07:08] p2099318 {__init__:53} INFO - rtg v0.5.0 from /home1/jain593/.conda/envs/nmt_toolkits_rtg/lib/python3.7/site-packages
Traceback (most recent call last):
  File "/home1/jain593/.conda/envs/nmt_toolkits_rtg/bin/rtg-serve", line 5, in <module>
    from rtg.serve.app import main
  File "/home1/jain593/.conda/envs/nmt_toolkits_rtg/lib/python3.7/site-packages/rtg/serve/app.py", line 7, in <module>
    from flask import Flask, request, jsonify, render_template, url_for, send_from_directory, Blueprint
ModuleNotFoundError: No module named 'flask'
```

**Comment by thammegowda** [comment]
Thanks for creating this issue.

if we run `pip install rtg[serve]`, it installs flask. Since we rarely use `rtg-serve`, and flask has its own set of dependencies unrelated to the core functionality of rtg, `flask` is made optional. 

https://github.com/isi-nlp/rtg/blob/0e25b86d9b0998078ac9f3424f20bf29df7138fa/setup.py#L47-L51

TODO: We need to update docs, and describe this behavior 
https://github.com/isi-nlp/rtg/blob/master/docs/50-serve.adoc
